import searchImg from "./../assets/3.svg";
import selectImg from "./../assets/1.svg";
import standoutImg from "./../assets/2.svg";

import style from "./Feature.module.css";

const Feature = () => {
	return (
		<div className={style["feature-container"]}>
			<div>
				<img className={style.img} src={searchImg} />
				<h2>Search</h2>
				<p>
					Simply add a keyword or a term related to your business in the slogan
					maker search box. Wait for the magic to happen.
				</p>
			</div>
			<div>
				<img className={style.img} src={selectImg} />
				<h2>Select</h2>
				<p>
					Choose from thousands of options generated by the slogan maker that
					fit your needs.
				</p>
			</div>
			<div>
				<img className={style.img} src={standoutImg} />
				<h2>Stand out</h2>
				<p>Congrats on your new slogan. It's time to win the world!</p>
			</div>
		</div>
	);
};

export default Feature;
